### ISSUE TITLE
Strong Named Project

### ISSUE THREAD

**Issue by Marknumskull** [PlayFab/consuldotnet#10]
Hi,

Would you be able to release a strongly named version of this library to Nuget?

I have a project which requires strong naming in assemblies and this failed the build. I was able to pull down the source and build myself but that's not as ideal as nuget as I will miss updates and such.

Thanks,

Mark

**Comment by highlyunavailable** [comment]
I don't see why not. Please note I'll be putting the snk file in the source tree, so it won't be usable as an _authenticated_ assembly, but I can set up strong naming easily enough.

**Comment by Marknumskull** [comment]
Hi,

Excellent, thanks for that!

Mark

**Comment by highlyunavailable** [comment]
This was fixed with 0.5.2.9:
https://www.nuget.org/packages/Consul/0.5.2.9

The Full Name of the assembly for this version is `Consul, Version=0.5.2.9, Culture=neutral, PublicKeyToken=20a6ad9a81df1d95`
