### ISSUE TITLE
Does ConsulClient properly handle infinite TimeSpan values?

### ISSUE THREAD

**Issue by smarts** [PlayFab/consuldotnet#107]
if i were to set `ConsulClientConfiguration.WaitTime` (for example) to `Timeout.InfiniteTimeSpan` would this library handle the value properly?

**Comment by highlyunavailable** [comment]
It will not, in the case of Timespans that get converted to Go Durations (e.g. "10s") to be passed to Consul, since the infinity case is not handled, but existing .NET functionality such as setting HttpClient timeouts will.
