### ISSUE TITLE
Consul.ConsulRequestException: Unexpected response, status code InternalServerError: rpc error making call: EOF

### ISSUE THREAD

**Issue by vasily-kirichenko** [PlayFab/consuldotnet#110]
https://github.com/Horusiath/Akka.Cluster.Discovery uses this client, see https://github.com/Horusiath/Akka.Cluster.Discovery/blob/ca04b544568fe700355d30a131b8a8362e7ae1fc/src/Akka.Cluster.Discovery.Consul/ConsulDiscoveryService.cs#L34. After a week of running without problems, I got the following exception:
```
03.02.2018 02:51:28.308 ERROR [Akka.Cluster.Discovery.Consul.ConsulDiscoveryService,  944] - Couldn't retrieve collection of nodes from external service. Is current node unreachable? Shutting down... Consul.ConsulRequestException: Unexpected response, status code InternalServerError: rpc error making call: EOF
   at Consul.GetRequest`1.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.Consul.ConsulDiscoveryService.<GetNodesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.DiscoveryService.<ReconcileClusterStateAsync>d__19.MoveNext()
```
(it's thrown here https://github.com/Horusiath/Akka.Cluster.Discovery/blob/ca04b544568fe700355d30a131b8a8362e7ae1fc/src/Akka.Cluster.Discovery.Consul/ConsulDiscoveryService.cs#L57)

Is it idiomatic to use `ConsulClient` this way (I mean create it once and use forever)? If it's not, is creating an instance for each request a nice idea? I see all the state is lazy, so I suspect it's quite expensive to recreate every time?

**Comment by highlyunavailable** [comment]
Yes, it is idiomatic to create it once per distinct cluster/datacenter connection and then reuse it forever. It's mostly that way due to the fact that HttpClient should be used in that way as well.

**Comment by vasily-kirichenko** [comment]
@highlyunavailable I'm not sure I understand you. I do reuse the client and it dies.

**Comment by highlyunavailable** [comment]
Re-make the request then? Or is the problem that you can no longer issue any requests?

**Comment by highlyunavailable** [comment]
The error `Unexpected response, status code InternalServerError: rpc error making call: EOF` means that Consul itself is encountering an error - the words "rpc error making call: EOF" are from Go.
