### ISSUE TITLE
Latest version is not available in Nuget

### ISSUE THREAD

**Issue by manupsunny** [PlayFab/consuldotnet#116]
The current latest version (`v0.7.2.4`) has a bug which prevents us from connecting to Consul server from a dotnet core project. We have tried cloning the repo, and the latest version seems to be working.

This [build](https://ci.appveyor.com/project/highlyunavailable/consuldotnet/build/0.7.2.465-master) has the latest code and is tagged as `v0.7.2.5`. But it's not available in Nuget. Could you please take a look at it and upload it to Nuget?

**Comment by anwright-ms** [comment]
Hooray for CI issues. Nuget has been updated.

**Comment by manupsunny** [comment]
Awesome. Thank you so much..
