### ISSUE TITLE
Enable HttpClientHandler pooling?

### ISSUE THREAD

**Issue by jiping-s** [PlayFab/consuldotnet#122]
Please consider to remove the [Obsolete] mark in the ConsulClient constructor which accepts HttpClient. It's required to handle pooling of HttpClient and/or HttpClientHandler, which ConsulClient doesn't provide.

The pooling is necessary and also recommended on Windows since [WinHttphandler](https://msdn.microsoft.com/en-us/library/system.net.http.winhttphandler%28v=vs.105%29.aspx?f=255&MSPPError=-2147217396) doesn't do that automatically and occupy lots of ports on client-side.

**Comment by highlyunavailable** [comment]
Can you give me a few more details about "pooling" here? You should be constructing a singleton ConsulClient object and reusing it across the rest of your app, much like HttpClient. I'm happy to make changes if needed but there's a single HttpClient constructed inside ConsulClient and reused for every call, and ConsulClient should be used in the same way.

**Comment by jiping-s** [comment]
singleton?! haven't thought about that.

Thanks :)
