### ISSUE TITLE
Cannot register service without a port

### ISSUE THREAD

**Issue by matthewcanty** [PlayFab/consuldotnet#32]
I've been using the following code to register services:

```
var serviceRegistration = new AgentServiceRegistration
{
    ...
};

Client.Agent.ServiceRegister(serviceRegistration);
```

It appears there is no way of _not_ setting a port. Am I wrong?

Port is an non-nullable int, which means it is always set, despite the attribute declaring nulls are ignored.

**Comment by highlyunavailable** [comment]
That attribute is wrong then and probably some copy-paste coding on my part. In Consul itself, you cannot register a service without a port. However, you should just leave the port as 0 to kind of indicate "not set" as port 0 is never valid, which should be the default value of int.

**Comment by matthewcanty** [comment]
Thanks for the info. I'll put some logic in at the reading end to remove the port `:0`
