### ISSUE TITLE
Add abortable lock

### ISSUE THREAD

**Issue by highlyunavailable** [PlayFab/consuldotnet#4]
If a lock is lost, add an abort of the action if it's not completed within the TTL.

**Comment by highlyunavailable** [comment]
https://msdn.microsoft.com/en-us/library/ty8d3wta.aspx

**Comment by rmul** [comment]
I have an issue and would like to check if you think this is related:
When a semaphore has been aqcuired and the session gets lost (for instance use the api to destroy the session) the RenewPeriodic method throws a "Session no longer exists" exception but catches that also and a cycle later a "Session timed out" exception is thrown which is not handled by the semaphore.acquire method.
If it is not related I am more than willing to create a new issue and help out with it.

**Comment by highlyunavailable** [comment]
@rmul Thanks for your report. That issue with semaphores and sessions is actually a separate issue and I'll look into it today.

This specific issue (#4) is more an enhancement - one of our developers requested that there be a type of lock that will thread.abort the code in the context of the lock if the lock was lost and it hadn't cancelled cleanly before the LockDelay expired.

**Comment by highlyunavailable** [comment]
@matt-augustine https://github.com/PlayFab/consuldotnet/blob/develop/Consul/Lock.cs#L774 Have fun!
