### ISSUE TITLE
Don't finalize me, just dispose

### ISSUE THREAD

**Issue by TMaster** [PlayFab/consuldotnet#40]
Hi,

I've seen that you use Finalizer in your code,

```CSharp
    ~ConsulClient()
        {
            if (HttpClient != null)
            {
                HttpClient.Dispose();
            }
        }
```

Is there any reason why the ConsulClient does not implement the IDisposable interface and you just add a Dispose method? (Finalizer are not so common in the .Net framework and should be used when there is absolutely no other way to achieve the goal. You're in the Managed world, Enjoy it my friend :))

As I see it the class should like like this:

```CSharp

public partial class ConsulClient : IDisposable

/* Some awesome code (without finalizers */

public Dispose()
{
 if (HttpClient != null)
            {
                HttpClient.Dispose();
            }
} 

What do you think?

**Comment by highlyunavailable** [comment]
My reasoning here: the Client should generally be constructed approximately once per program unless multiple Consul configurations are required. It is an extremely long-lived object that only needs to be created once and should be referred to many times. I do not want to create and dispose of the HttpClient regularly either, since all of the headers and such remain the same, so I make a Client, make an HttpClient, then tear down the HttpClient only when the `Client` is finally cleaned up.

I thought HttpClients were supposed to be long lived as well, so that's why I only created one and reused it.

If I didn't want to use a finalizer, I'd probably switch to a using block that constructed an HttpClient in every `Execute()` call (e.g. here: https://github.com/PlayFab/consuldotnet/blob/master/Consul/Client.cs#L530)

In fact, I should also be disposing of `config.Handler` as well if it's not null - looks like I should add that somewhere.

What are your thoughts, given the info above?

**Comment by TMaster** [comment]
I'm sorry I don't believe that creating HttpClient on every REST call is the solution.
Like you said, the HttpClient (like the ConsulClient) should live long inside the application.

Now I want to refer to your answer: 
>  I make a Client, make an HttpClient, then tear down the HttpClient only when the `ConsulClient` is finally cleaned up.

If I've understood you correctly you are saying that you want to dispose the `HttpClient` only when there is absolutely no way that the user will issue another call http request.

Well the `IDisposable` interface is the most common solution to the address this scenario. users should call `Dispose()` when they don't need the client anymore. so they don't suppose to issue another request. and if they do, I'm pretty sure that the HttpClient will throw  [ObjectDisposedException](https://msdn.microsoft.com/en-us/library/system.objectdisposedexception(v=vs.110).aspx) which pretty much tell the user, that the HttpClient can not be further used because you disposed it :) 

If you really want to be a saint you can add a data member indicating whether the client (`ConsulClient`) is disposed (e.g. create a bool var (with a good name of _isDisposed) initialize it to false in  the constructor and assign true on the `Dispose()` call).  Now on the `Execute()` method you can do something like this:

```CSharp
public async Task<QueryResult<T>> Execute(CancellationToken ct)
        {
          if(_isDisposed)
              {
                  throw new ObjectDisposedException([Apply very indicative exception message]);
              }

            var start = DateTime.UtcNow;
            var result = new QueryResult<T>();

            var message = new HttpRequestMessage(HttpMethod.Get, BuildConsulUri(Endpoint, Params));
            var response = await Client.HttpClient.SendAsync(message, ct).ConfigureAwait(false);

```

This is a trick I've seen couple of times while digging into the .Net framewok.

What do you think?

Did I made myself clear? (Again, regarding what you told me I believe that `IDisposable~ is the right solution in this case)

Thanks :wink:

**Comment by highlyunavailable** [comment]
You've definitely made yourself clear. The fact that `ConsulClient` is a long-lived object, and that I have not required this before makes me hesitant to add `IDisposable` without keeping a finalizer. However, given this code example here: https://msdn.microsoft.com/en-us/library/system.idisposable.dispose%28v=vs.110%29.aspx

I think there's a good way around this. Make the `ConsulClient` implement `IDisposable` but also keep the finalizer and have it call `Dispose(false)`, as well as suppressing finalization if disposed (so it's never run if the user properly cleans up.

**Comment by highlyunavailable** [comment]
Given that the "Make a Dispose method, and also call it in the Finalizer, but suppress finalize if Dispose is called" pattern is "The IDisposable Pattern" according to MS, I'm going to consider this one fixed based on the changes I made in d3a65aca0ed62d7fd500f401a134202e061ebb6e. This also means that existing code will not break, but new code should use `Dispose()`.

**Comment by TMaster** [comment]
I dig a little bit in the .Net Framework to be sure in what I'm about to say.

According to CLR via C# (fourth edition pages 525-526) the garbage collector reclaims memory for objects inside the heap with no references. The finalize method is useful only when you have resources that you want to close (for example open sockets or handles to files in the file system). You my friend has none of those, you don't hold the actual socket, but a managed Stream to it. therefore you should not call finalize, but let the framework do it's magic and call to the finalize itself (if the user of course did not call `Dispose()` himself).

Having finerlizer in your code actually may harm the application, because there is a dedicated (single) thread that finalize all the objects (that has finalizers of course), and until the object is not fully finzelized the GC can not reclaim the memory. Moreover, the user may (by mistake) still use the Client somewhere in the code exactly when the Finelizer thread call the finalize method (it is a long shout, but I saw it happen).

For the `Disposable Pattern` you mentioned, I looked up in the [HttpClient  source code](https://www.symbolsource.org/Public/Metadata/NuGet/Project/HttpClient/0.5.0/Release/.NETFramework,Version%3Dv4.0/Microsoft.Net.Http/Microsoft.Net.Http/System/Net/Http/HttpClient.cs?ImageName=Microsoft.Net.Http) and saw that the HttpClient himself uses this pattern.

I think that makes the Finazlier in the ConsulClient redundant: either the user called `Dispose()` and the Finelizer of the HttpClient is not longer needed, considering this code in the HttpClient:

```CSharp

 public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
```

And if this is not the case (and the user forgot to call `Dispode()`), **Only the HttpClient will be transferred to the Finzlier's queue, when the other memory allocated for the ConsulClient would be reclaimed by the GC.**

I think this is the desired behavior, Dont you think so?

**Comment by highlyunavailable** [comment]
Alright, I think I finally get what you're saying. Whatever portion of the HttpClient that needs finalizing will handle the finalizing, so I only need to manually dispose of the client (and suppress finalizing if manually disposed) if the user calls `Dispose()` themselves.

**Comment by highlyunavailable** [comment]
Okay, fixed in ccebafbe7462a168c6bf4160e2f744e98ec224a0 for real now. I'm not going to cut a new release for this because the Finalizer was already a no-op since d3a65aca0ed62d7fd500f401a134202e061ebb6e, it just called `Dispose(false)` which then just set `disposedvalue` to `true` and nothing else since the managed disposal was guarded by the `if (disposing)` block.

Good catch, and thanks for being patient with me.

**Comment by jhickson** [comment]
Hello,

Is there any reason you made `ConsulClient` implement `IDisposable` but didn't make `IConsulClient` extend `IDisposable`?  I'd rather use `IConsulClient` as I can then mock it for unit testing but that makes disposing trickier.  I can get round it though if it's not something you want to do (I know some people disagree with composing interfaces from other interfaces).

**Comment by highlyunavailable** [comment]
@jhickson Nope, I just forgot. I'll drop a new release in a couple minutes that has the correction.

**Comment by jhickson** [comment]
@highlyunavailable  Actually before you do that - I've got as far as trying to mock `ICatalogEndpoint` and return a response from `Service()` but I cannot construct a response because `QueryResult<>.Response` has an internal setter.  Would it be possible to make it public, please?  Should I open an issue rather than go off-topic here?

**Comment by highlyunavailable** [comment]
Yeah, please open an issue. I'm not really sure what exactly is involved in the process of mocking one of these since all of the testing done on this library is done via what would be technically integration tests against a normal consul agent.

**Comment by jhickson** [comment]
Added as #48, thanks.
