### ISSUE TITLE
Publishing service state via API sends incorrect note string

### ISSUE THREAD

**Issue by v-karbovnichiy-parc** [PlayFab/consuldotnet#45]
Method `Agent.UpdateTTL` has parameter `note` which value gets encoded via `Uri.EscapeDataString(note)` before adding to web request parameters dictionary. It is incorrect because in method `ConsulRequest.BuildConsulUri` all uri parameter values gets encoded via `Uri.EscapeDataString`. So when we publish some note with service state, its value gets encoded 2 times.

Correct standard service check (proves that it is not consul core bug):
![image](https://cloud.githubusercontent.com/assets/16113971/13527837/89f4a8a2-e22b-11e5-83ef-3bd8f515a568.png)

Incorrect service check:
![image](https://cloud.githubusercontent.com/assets/16113971/13528196/e4c2f872-e22d-11e5-9635-fa2ccdc88ee2.png)

I can send PR with bug fix and tests.

**Comment by highlyunavailable** [comment]
Thanks for finding the bug and submitting this issue! I'm traveling right now so my ability to fix this quickly is limited, but I'd be happy to review and accept your PR. Please send the PR against the `develop` branch rather than `master`.

**Comment by highlyunavailable** [comment]
This should be resolved and will be available in package version [0.6.3.3](https://www.nuget.org/packages/Consul/0.6.3.3) and onwards.
