### ISSUE TITLE
Specifying a WaitTime using ConsulClientConfiguration.WaitTime results in a "bad request"

### ISSUE THREAD

**Issue by jhickson** [PlayFab/consuldotnet#50]
Hi,

If I set `ConsulClientConfiguration.WaitTime` to a value (I've tried 10 seconds and 5 minutes, so sane values) then when I use `ICatalogEndpoint.Service` it fails with the error message:

> Unexpected response, status code BadRequest: Invalid wait time

If I use `QueryOptions` instead then it works.

I've not tried any other calls so this might not affect just `ICatalogEndpoint.Service`.

**Comment by highlyunavailable** [comment]
It's a bug that would affect all endpoints. Consul wants a Go duration string (which is either a numeric string followed by a unit, or _nanoseconds_, not milliseconds) for the WaitTime. You hit a fairly old codepath that was just taking a time and returning the raw Millisecond string. I've added a fix and a test and a new release is forthcoming.

**Comment by highlyunavailable** [comment]
Thanks for reporting this @jhickson - it has been resolved along with a couple of other duration conversion bugs and is available as 0.6.4.1 on Nuget: https://www.nuget.org/packages/Consul/0.6.4.1
