### ISSUE TITLE
LockTryOnce behaviour

### ISSUE THREAD

**Issue by tavisca-rajeshs** [PlayFab/consuldotnet#60]
Hi,
    When specifying **LockWaitTime** in **LockOptions**, if **LockTryOnce** is set, the expected behavior is to **block** for the lock acquisition for a max of LockWaitTime **just once**,
The blocking GET call that happens for the lock doesn't block until the wait time is coupled with **index**  value. But the index value isn't obtained until after the first call is made(which ignores the wait time since index to wait on isn't supplied) and this first call fulfills the  **LockTryOnce** criteria and throws an exception after that. So the blocking wait never happens in case LockTryOnce is set.
Can this be fixed so that even in case the requested lock key is already acquired, the wait happens for the specified wait time once?

**Comment by highlyunavailable** [comment]
Thanks for reporting this! I believe that this specific time wait was behavior that was added after TryOnce was introduced that I never got around to porting. It will be fixed in 0.6.4.7 which is on nuget now: https://www.nuget.org/packages/Consul/0.6.4.7

**Comment by tavisca-rajeshs** [comment]
Thanks for the quick fix.
