### ISSUE TITLE
.NET Core Consul Conguration Provider

### ISSUE THREAD

**Issue by johnmckinzie** [PlayFab/consuldotnet#65]
This would be an enhancement request to create a custom configuration provider that uses Consul under the hood.

https://docs.asp.net/en/latest/fundamentals/configuration.html#writing-custom-providers

**Comment by highlyunavailable** [comment]
Thanks for this request. The scope of this project is to only provide an API for Consul that closely mimics the official Go API from the Hashicorp developers with minor changes to make it more idiomatic/ergonomic in .NET specific ways, not to add any particular .NET-stack specific functionality. I'd be happy to assist you or someone else that wants to write a custom configuration provider, though - my email is in my Github profile or feel free to continue in this issue.

**Comment by johnmckinzie** [comment]
Understanable.

**Comment by lvermeulen** [comment]
@johnmckinzie It's a great idea; I'll take it on in [Nanophone](https://github.com/lvermeulen/Nanophone/issues/18).
