### ISSUE TITLE
dotnet client has a really bad performance

### ISSUE THREAD

**Issue by egmkang** [PlayFab/consuldotnet#66]
i create a dev server on `192.168.15.235` and my c# client is on `192.168.15.24`.

the simple sample cost about `150ms` every request `KV.Get`. and i used wireshark to test the real latency. and the one single request cost about `1ms` when the response came back.

```
50	16:22:26.949815	192.168.15.24	192.168.15.235	HTTP	154	GET /v1/kv/hello HTTP/1.1 
51	16:22:26.950450	192.168.15.235	192.168.15.24	HTTP	337	HTTP/1.1 200 OK  (application/json)
```

**Comment by highlyunavailable** [comment]
Thanks for reporting this issue! This is not typically the performance that tends to be seen in other environments, so I'd like to get some additional information from you. Would it be possible to provide the test code here or in a gist? Also, are you using .NET Core, .NET 4.x, or Mono to run your sample?

**Comment by highlyunavailable** [comment]
I've created a tiny test sample based off of the "set a KV, get a KV" in the readme, and I am seeing 200ms+ latencies but only for the very first request. Some performance profiling appears to indicate it's JSON.NET lazily initializing. Subsequent requests are near-wire-speed latencies.

Could you please confirm that you are seeing high latencies past the first request? An easy way to test would be to loop it a few times:

```c#
var w = new System.Diagnostics.Stopwatch();
for (int i = 0; i < 10; i++)
{
    w.Restart();
    var getPair = await client.KV.Get("hello");
    Console.WriteLine(w.ElapsedMilliseconds);
}
```

**Comment by egmkang** [comment]
next Monday i will confirm the real problem, i'm using .net framework 4.6.2

**Comment by egmkang** [comment]
when i use default ConsulClient, it's really fast.
when i use code like this:
```
var config = new ConsulClientConfiguration();
config.Address = new Uri("http://192.168.15.235:8500");
var client = new ConsulClient(config);
```

every request cost about 150~200ms, what's the problem of my init codes?

**Comment by highlyunavailable** [comment]
The default `ConsulClient` accesses 127.0.0.1:8500, so I'm not surprised it's fast. It's localhost after all.

I'm not able to reproduce this with a vagrant box server either. My test code looks like this:

```c#
public static async Task HelloConsul()
{
    var config = new ConsulClientConfiguration();
    config.Address = new Uri("http://10.3.0.10:8500");
    using (var client = new ConsulClient(config))
    {
        var putPair = new KVPair("hello")
        {
            Value = Encoding.UTF8.GetBytes("Hello Consul")
        };

        var putAttempt = await client.KV.Put(putPair);
        var w = new Stopwatch();
        for (int i = 0; i < 5; i++)
        {
            w.Restart();
            var getPair = await client.KV.Get("hello");
            Console.WriteLine(w.ElapsedMilliseconds);
        }
    }
}
```

And my timer results are:
```
61
0
0
0
0
```

Removing the Put does not change the timings appreciably.

I also tested against http://demo.consul.io with this code:

```
public static async Task GetDemoConsulKey()
{
    var config = new ConsulClientConfiguration();
    config.Address = new Uri("http://demo.consul.io");
    config.Datacenter = "sfo1";
    using (var client = new ConsulClient(config))
    {
        var w = new Stopwatch();
        for (int i = 0; i < 5; i++)
        {
            w.Restart();
            var getPair = await client.KV.Get("global/time");
            Console.WriteLine(w.ElapsedMilliseconds);
        }
    }
}
```

Latency times in Wireshark matched what I was seeing in the stopwatch delay after the first request as well.

Ideally, please make a [Gist](https://gist.github.com/) of your complete test program if possible and put a link to it in this issue. If you aren't able to provide the test code, can you please confirm you are not creating a ConsulClient for each request? It shouldn't matter but they generally are fairly expensive to create, and should be reused as shown. Also, are you using the nuget package Consul.NET 0.6.4.7 or some other version? I can't think of anything that I would have fixed that could cause this but that's worth checking.

**Comment by egmkang** [comment]
https://gist.github.com/egmkang/ef139881056db0bac104e9ec0a322809

on my win7(64bit), .net framework 4.5 and 4.6.1, 100 get request cost about 12.5 seconds.
on my linux(192.168.15.235), mono 4.4.2,  100 request cost about 0.047 seconds.

**Comment by egmkang** [comment]
Consul.net version is 0.6.4.7

**Comment by highlyunavailable** [comment]
I am not able to repro this at all, unfortunately. I've got a Windows 8 machine requesting data from my Ubuntu vagrant box at 10.3.0.10, and I get:

4.5:
```
Consul Get
<Main>b__0        100 op 0.053 s 533955.900 ns/op
```

4.6.1:
```
Consul Get
<Main>b__0        100 op 0.081 s 809401.950 ns/op
```

At this point, I don't really know what to say - I'd be happy to fix it or accept a PR if you could point me at what's wrong, but I'm unfortunately going to have to ask that you try to profile the code yourself to see what's going on. I can try setting up a couple AWS machines some time this week and running the test there but it would probably be faster for you to use your own tools to try to see what's going on.

One other thing that you could try is the [prerelease version](https://www.nuget.org/packages/Consul/0.7.0-rc1) - you'll want to rework the config a bit after upgrading:

Replace the lines that read:
```
var config = new ConsulClientConfiguration();
config.Address = new Uri("http://192.168.15.235:8500");
var client = new ConsulClient(config);
Stopwatch sw = new Stopwatch();
```

with:

```
var client = new ConsulClient((config) => { config.Address = new Uri("http://10.3.0.10:8500"); });
```

I doubt it will help but it's worth a shot since I reworked a bunch of the client stuff in the 0.7.0 release.

**Comment by lvermeulen** [comment]
@egmkang Are you running this test while firewall, proxy or anti-virus software is running?

**Comment by egmkang** [comment]
@lvermeulen the wireshark result shows the network latency is very low, i test it for several times.

**Comment by egmkang** [comment]
@highlyunavailable i test 0.7.0, it's same like 0.6.4.7

**Comment by egmkang** [comment]
i know what's the real problem, my **ShadowSocks** hook all http request, after i close ShadowSocks, the request get fast, and 100 request cost about 70~100ms now .

in china, without ShadowSocks or vpn, i cannot access stackoverflow, github ......

**Comment by lvermeulen** [comment]
Right, a proxy. Can you configure it to bypass local addresses?

**Comment by egmkang** [comment]
it seems like ConsulDotNet using HttpClient to request the server

**Comment by egmkang** [comment]
```
var httpClientHandler = new HttpClientHandler();
httpClientHandler.Proxy = null;
httpClientHandler.UseProxy = false;
var httpClient = new HttpClient(httpClientHandler);
```

i use this to ignore system proxy, and it works fine

**Comment by highlyunavailable** [comment]
Yeah, that will do it. Glad you got this figured out.
