### ISSUE TITLE
Depends on .NET 4.5.1 in 0.7.0 

### ISSUE THREAD

**Issue by kpa6uk** [PlayFab/consuldotnet#67]
I have large suolution with 300+ projects targeting .NET 4.5 and I have no chance to target .NET Framework 4.5.1 in next 6 month. Last NuGet package targeting this .NET is v0.6.4.7.

So what can I do now to use Consul v.0.7?

**Comment by highlyunavailable** [comment]
Thanks for letting me know about this! I'm sorry to say that it was an inadvertent "upgrade" and will be corrected in a point release that I'm testing right now.

**Comment by highlyunavailable** [comment]
A new release with a fixed framework version has been published as [0.7.0.2](https://www.nuget.org/packages/Consul/0.7.0.2) to Nuget and will be available once Nuget indexing happens. Thanks again!
