### ISSUE TITLE
Unable to alter Consul server endpoint from localhost:8500 using ConsulClient(Action<...>) approach

### ISSUE THREAD

**Issue by frostshoxx** [PlayFab/consuldotnet#68]
Hi there,

I would to change the Consule server endpoint from localhost:8500 to something else. I tried to instantiate the client object using the following code:

```
using (var client = new ConsulClient(x => new ConsulClientConfiguration() 
{ Address = new Uri("http://consul.local:8500") }))
            {
....

}
```

However when I run the code, the result looks like it's still pointing to localhost:8500. Am I doing the configuration wrong?

Thank you for your help.

**Comment by frostshoxx** [comment]
Note that using this approach works, but the note specify that it will go obsolete by version 0.8

```
  var remoteConfig = new ConsulClientConfiguration()
            {
                Address = new Uri("http://consul.local:8500")
            };

            using (var client = new ConsulClient(remoteConfig)){....}
```

**Comment by highlyunavailable** [comment]
Thanks for reporting this!

There's actually a ConsulClientConfiguration local to the ConsulClient object that is visible inside the action's scope as the variable you specify in the action.

For example, your example should read:

```c#
using (var client = new ConsulClient((c) =>{ c.Address = new Uri("http://consul.local:8500")}) {
    // Do something with client
}
```

**Comment by frostshoxx** [comment]
Ah! My syntax was wrong then. Thank you!

**Comment by highlyunavailable** [comment]
All the actions are like that, too - you can see examples in the tests at https://github.com/PlayFab/consuldotnet/blob/master/Consul.Test/ClientTest.cs#L191

This is unfortunately an outstanding bug - I need to document the whole API better especially since some of it is breaking away from the official Consul API style but I'm maintaining this as a very part-time thing.
