### ISSUE TITLE
Does this library support Linux?

### ISSUE THREAD

**Issue by psibernetic** [PlayFab/consuldotnet#80]
Doesn't appear to due to the System.Net.Http.WinHttpHandler reference...

**Comment by highlyunavailable** [comment]
It does! That name is somewhat of a misnomer, that's what is in Core, which works on both Linux and Windows.

**Comment by psibernetic** [comment]
Thanks for the feedback, yeah that is deceptive! 

Any idea on how to solve the issue I am getting?

http://stackoverflow.com/questions/42472536/can-a-library-that-depends-on-system-net-http-winhttphandler-be-deployed-to-linu

**Comment by psibernetic** [comment]
I haven't ran the dotnet sdk installer since I was doing a Self-Contained deployment, but if that is my problem I will.

**Comment by psibernetic** [comment]
That solves it, disappointing. Thanks!

**Comment by highlyunavailable** [comment]
I answered your SO post, but I was able to get it working with a self-contained deployment.

**Comment by psibernetic** [comment]
Copying here: I think it is the "platform": true configuration that causes the issue. I have moved to .CSPROJ project structure, and that is no longer a setting. Not sure where it is now!
