### ISSUE TITLE
Leave and Reload method missed in IAgentEndpoint

### ISSUE THREAD

**Issue by vincentshow** [PlayFab/consuldotnet#85]
I  notice there're leave and reload functions in Agent.cs like these:

public Task<WriteResult> Leave(string node, CancellationToken ct = default(CancellationToken))
public Task<WriteResult> Reload(string node, CancellationToken ct = default(CancellationToken))

but I can't call them in ConsulClient.Agent. After reading  source code, I found there were no definitions in IAgentEndpoint.cs. Is this your original purpose?

**Comment by highlyunavailable** [comment]
Nope, those should be in IAgentEndpoint as well. Sorry about that.

**Comment by highlyunavailable** [comment]
This has been resolved in [0.7.2.3](https://www.nuget.org/packages/Consul/0.7.2.3).
