### ISSUE TITLE
QueryOptions not applied to request

### ISSUE THREAD

**Issue by Crozin** [PlayFab/consuldotnet#98]
It seems that library ignores `QueryOptions` parameter:

            var options = QueryOptions.Default;
            options.Datacenter = "myCustomDc";

            var qr = await cc
                .Health
                .Service("myService", "myTag", true, options);

Results in query for `/v1/health/service/myService?tag=myTag&passing=1` instead of `/v1/health/service/myService?tag=myTag&passing=1&dc=myCustomDc`

**Comment by highlyunavailable** [comment]
This is incorrect usage. `QueryOptions.Default` should not be used/modified. Make a new QueryOptions instance then set your custom DC, for example:

            var options = new QueryOptions();
            options.Datacenter = "myCustomDc";

            var qr = await cc
                .Health
                .Service("myService", "myTag", true, options);
